### ISSUE TITLE
Could not evaluate: undefined method `[]' for nil:NilClass on docker phusion/baseimage

### ISSUE THREAD

**Issue by reinaldomendes** [mayflower/puppet-php#173] opened 2016-04-03 21:48 UTC
I recently have changed my vagrant box from ubuntu 14.04 on virtualbox to phusion/baseimage on docker.

I'm running on puppet 4.4.1

Bellow are my simple configuration to test.

```puppet
# environments/test/manifests/site.pp
node default{
  include php
}
```

```yaml
#hieradata
---
php::repo::ubuntu::ppa: 'ondrej/php5-5.6'
php::manage_repos: true
php::pear: true
php::cli: true
php::dev: true
php::composer: false
php::composer::auto_update: false
php::settings: &php_settings
  'PHP/display_errors' : 'on'
  'PHP/error_reporting' : 'E_ALL & ~E_NOTICE & ~ E_DEPRECATED'
  'PHP/max_execution_time': 600
  'PHP/max_input_time': '300'
  'PHP/memory_limit': '512M'
  'PHP/post_max_size': '64M'
  'PHP/upload_max_filesize': '64M'
  'Date/date.timezone': 'America/Sao_Paulo'
  'PHP/short_open_tag': 'off'
php::cli::settings:
  << : *php_settings
php::fpm::settings:
  << : *php_settings
php::fpm::config::pool_purge: true
php::fpm::pool::security_limit_extensions: '.php'
php::fpm::pools: {  
  }
php::extensions:
  json: {}
  redis: {}
  imagick: {}
  mcrypt : {}
  mysqlnd: {}
  gd: {}
  curl: {}
  xmlrpc: {}
  #soap: {} Native on php5.6
  opcache: #embed on php5.6 but configurable
      ensure: absent
      settings:
       opcache.enable: 1
       opcache.max_accelerated_files: 4096
       opcache.revalidate_freq: 10
       opcache.revalidate_path: 1
       opcache.save_comments: 1
       opcache.load_comments: 1
       opcache.enable_file_override: 1

  lzf:
    provider: pecl
    header_packages:
    - build-essential
    - php-pear
php::fpm: true
```

```bash
puppet apply  test/manifests/site.pp  --verbose --hiera_config=hiera.yaml  --environmentpath=. --environment=test
```
```
Warning: Undefined variable 'lsbminordistrelease'; 
   (file & line not available)
Notice: Compiled catalog for puppet-agent.vagrant.loc in environment test in 0.61 seconds
Info: Applying configuration version '1459719803'
Notice: /Stage[main]/Php/Php::Extension[lzf]/Package[pecl-lzf]/ensure: created
Info: Php::Extension[lzf]: Scheduling refresh of Service[php5-fpm]
Error: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]: Could not evaluate: undefined method `[]' for nil:NilClass
Notice: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]: Triggered 'refresh' from 1 events
Info: Class[Php::Fpm::Service]: Unscheduling all events on Class[Php::Fpm::Service]
Notice: /Stage[main]/Php::Fpm/Anchor[::php::fpm::end]: Dependency Service[php5-fpm] has failures: true
Warning: /Stage[main]/Php::Fpm/Anchor[::php::fpm::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Anchor[php::end]: Dependency Service[php5-fpm] has failures: true
Warning: /Stage[main]/Php/Anchor[php::end]: Skipping because of failed dependencies
Info: Class[Php]: Unscheduling all events on Class[Php]
Notice: Applied catalog in 0.57 seconds
```

**Comment by reinaldomendes** [comment] 2016-04-03 21:57
```bash
puppet apply  -e "include '::php'"  --verbose  --environmentpath=. --environment=test 
```
```
Warning: Undefined variable 'lsbminordistrelease'; 
   (file & line not available)
Notice: Compiled catalog for puppet-agent.vagrant.loc in environment test in 0.52 seconds
Info: Applying configuration version '1459720601'
Error: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]: Could not evaluate: undefined method `[]' for nil:NilClass
Notice: /Stage[main]/Php::Fpm/Anchor[::php::fpm::end]: Dependency Service[php5-fpm] has failures: true
Warning: /Stage[main]/Php::Fpm/Anchor[::php::fpm::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Php/Anchor[php::end]: Dependency Service[php5-fpm] has failures: true
Warning: /Stage[main]/Php/Anchor[php::end]: Skipping because of failed dependencies
Notice: Applied catalog in 0.16 seconds
```

**Comment by mmoll** [comment] 2016-04-03 21:59
I suspect the package `lsb-release` is not installed.

**Comment by reinaldomendes** [comment] 2016-04-03 22:01
lsb-release is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

**Comment by mmoll** [comment] 2016-04-03 22:03
BTW, which version of puppet-php are you using? (git commit, if not a numbered version)

**Comment by reinaldomendes** [comment] 2016-04-03 22:05
In module php metadata.json was version was  "3.4.2",

**Comment by reinaldomendes** [comment] 2016-04-03 22:08
```bash
 puppet module list --tree --environmentpath=. --environment=test
```
```
├─┬ mayflower-php (v3.4.2) [/tmp/vagrant-puppet/environments/modules]
    │ ├── puppetlabs-apt (v2.2.2) [/tmp/vagrant-puppet/environments/modules]
    │ ├── puppetlabs-inifile (v1.5.0) [/tmp/vagrant-puppet/environments/modules]
    │ ├── darin-zypprepo (v1.0.2) [/tmp/vagrant-puppet/environments/modules]
    │ └─┬ example42-yum (v2.1.27) [/tmp/vagrant-puppet/environments/modules]
    │   └── example42-puppi (v2.1.13) [/tmp/vagrant-puppet/environments/modules]
```

**Comment by reinaldomendes** [comment] 2016-04-03 22:13
My facter doesn't shows lsb on docker phusion/baseimage.

```bash 
facter os
```
```
{
  architecture => "amd64",
  distro => {
    codename => "trusty",
    description => "Ubuntu 14.04.4 LTS",
    id => "Ubuntu",
    release => {
      full => "14.04",
      major => "14.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "14.04",
    major => "14.04"
  },
  selinux => {
    enabled => false
  }
}
```

If I run in my host machine that have puppet too its returns.

```
{
 "name"=>"Ubuntu", 
 "family"=>"Debian",
 "release"=>{
     "major"=>"14.04", "full"=>"14.04"
  }, 
  "lsb"=>{
      "distcodename"=>"trusty", 
       "distid"=>"Ubuntu", 
       "distdescription"=>"Ubuntu 14.04.4 LTS",
       "distrelease"=>"14.04", 
       "majdistrelease"=>"14.04"
    }
}
```

**Comment by reinaldomendes** [comment] 2016-04-03 22:25
```puppet
class php::fpm::service(
 $service_name = $::php::params::fpm_service_name,
  $ensure       = 'running',
  $enable       = $::php::params::fpm_service_enable,
) inherits ::php::params {
# ....
service { $service_name:
    ensure     => $ensure,
    #enable     => $enable, # I just comment enable option inside a module #line :39
    hasrestart => true,
    restart    => $restart,
    hasstatus  => true,
  }
```

So when I run, I still seeing  "Warning lsbminordistrelease", but the catalogs runs
```bash
puppet apply  -e "include '::php'"  --verbose  --environmentpath=. --environment=test 
```
```
Warning: Undefined variable 'lsbminordistrelease'; 
   (file & line not available)
Notice: Compiled catalog for puppet-agent.vagrant.loc in environment test in 0.51 seconds
Info: Applying configuration version '1459722101'
Notice: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Php::Fpm::Service/Service[php5-fpm]: Unscheduling refresh on Service[php5-fpm]
Notice: Applied catalog in 0.17 seconds
```

**Comment by mmoll** [comment] 2016-04-03 22:26
Facter 3.x does things different here, however, I can't reproduce this issue on a clean install of Ubuntu/trusty with Puppet 4.4.1 and Facter 3.1.5, so I'm inclined to blame that image or Docker.

**Comment by reinaldomendes** [comment] 2016-04-03 22:31
I think its the docker because on ubuntu trusty over virtualbox it was working.
The default docker image of ubuntu has a series of problems, the phusion/baseimage solve many things like zombie processes that appears on default ubuntu over docker, etc..

**Comment by reinaldomendes** [comment] 2016-04-03 22:33
Note: If I enable strict_variables=true on puppet.conf the warning disapear.

**Comment by reinaldomendes** [comment] 2016-04-03 22:38
I think it was correlated with it issue.

https://ask.puppetlabs.com/question/10955/issues-with-ubuntu-docker-image-and-puppetlabs-mysql/

On host ubuntu initctl was 1.12.1
On docker images initctl was 8.21

**Comment by mmoll** [comment] 2016-04-03 22:41
We don't even use `lsbminordistrelease` in this module (but other lsbfacts, so facter 3.x support would need some more checking). Anyway, as this is not reproducible on a clean install, would it be ok to close this issue?

**Comment by reinaldomendes** [comment] 2016-04-03 22:42
It's  solve my problem.


```bash
mv /sbin/initctl /sbin/oldinitctl
echo -e '#!/bin/bash\nif [ $1 == "--version" ]\nthen\n  echo "initctl (upstart 1.12.1)"\nfi\n/sbin/oldinitctl "$@"' > /sbin/initctl
chmod 755 /sbin/initctl
```

**Comment by reinaldomendes** [comment] 2016-04-03 22:42
Thanks.

**Closed** 2016-04-08 13:34 UTC
